/**
 * API Endpoints Configuration
 * Aligned with backend routes in src/routes/index.js
 */

const v1 = 'api/v1';

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN:          `${v1}/auth/login`,
    REGISTER:       `${v1}/auth/register`,
    VERIFY_OTP:     (id: string | number) => `${v1}/auth/verify/${id}`,
    RESEND_OTP:     (id: string | number) => `${v1}/auth/resendOTP/${id}`,
    FORGOT_PASSWORD:`${v1}/auth/forgot`,
    RESET_PASSWORD: (id: string | number) => `${v1}/auth/reset/${id}`,
    ME:             `${v1}/auth/me`,
    REFRESH:        `${v1}/auth/refresh`,
    LOGOUT:         `${v1}/auth/logout`,
  },
  TEAM: {
    LIST:        `${v1}/team`,
    CREATE:      `${v1}/team`,
    DELETE_MANY: `${v1}/team`,
    DETAIL:      (id: string | number) => `${v1}/team/${id}`,
    UPDATE:      (id: string | number) => `${v1}/team/${id}`,
    DELETE:      (id: string | number) => `${v1}/team/${id}`,
  },
  DEPARTMENT: {
    LIST:      `${v1}/department`,
    CREATE:    `${v1}/department`,
    DETAIL:    (id: string | number) => `${v1}/department/${id}`,
    UPDATE:    (id: string | number) => `${v1}/department/${id}`,
    DELETE:    (id: string | number) => `${v1}/department/${id}`,
    DIVISIONS: (id: string | number) => `${v1}/department/${id}/divisions`,
  },
  ROLE: {
    LIST: `${v1}/user/roles`,
  },
  INVITE: {
    LIST:        `${v1}/invite`,
    CREATE:      `${v1}/invite`,
    DELETE_MANY: `${v1}/invite`,
    PREVIEW:     (token: string) => `${v1}/invite/token/${token}/preview`,
    REDEEM:      `${v1}/invite/redeem`,
    DETAIL:      (id: string | number) => `${v1}/invite/${id}`,
    UPDATE:      (id: string | number) => `${v1}/invite/${id}`,
    DELETE:      (id: string | number) => `${v1}/invite/${id}`,
    ACCEPT:      (id: string | number) => `${v1}/invite/${id}/accept`,
  },
  USER: {
    ME_UPDATE:   `${v1}/user/me`,
    LIST:        `${v1}/user`,
    CREATE:      `${v1}/user`,
    UPDATE_MANY: `${v1}/user`,
    DELETE_MANY: `${v1}/user`,
    DETAIL:      (id: string | number) => `${v1}/user/${id}`,
    UPDATE:      (id: string | number) => `${v1}/user/${id}`,
    DELETE:       (id: string | number) => `${v1}/user/${id}`,
    BULK_DELETE:  `${v1}/user/bulk-delete`,
  },
  PROJECT: {
    LIST:   `${v1}/project`,
    CREATE: `${v1}/project`,
    SAVED:  `${v1}/project/saved`,
    DETAIL: (id: string | number) => `${v1}/project/${id}`,
    UPDATE: (id: string | number) => `${v1}/project/${id}`,
    DELETE: (id: string | number) => `${v1}/project/${id}`,
    SAVE:      (id: string | number) => `${v1}/project/${id}/save`,
    UNSAVE:    (id: string | number) => `${v1}/project/${id}/save`,
    EXTENSION: (id: string | number) => `${v1}/project/${id}/extension`,
  },
  TIMESHEET: {
    WEEKLY:          `${v1}/timesheet/weekly`,
    REQUESTS:        `${v1}/timesheet/requests`,
    MY_REQUESTS:     `${v1}/timesheet/my-requests`,
    POLICIES:        `${v1}/timesheet/time-off/policies`,
    REQUEST_TIME_OFF:`${v1}/timesheet/time-off/request`,
    CREATE_ENTRY:    `${v1}/timesheet/entry`,
    CLOCK_IN:        `${v1}/timesheet/clock-in`,
    CLOCK_OUT:       `${v1}/timesheet/clock-out`,
    FORCE_CHECKOUT:  `${v1}/timesheet/force-checkout`,
    TODAY:           `${v1}/timesheet/today`,
    DETAIL:          (id: string | number) => `${v1}/timesheet/entry/${id}`,
    UPDATE:          (id: string | number) => `${v1}/timesheet/entry/${id}`,
    DELETE:          (id: string | number) => `${v1}/timesheet/entry/${id}`,
    REQUEST_EDIT:    (id: string | number) => `${v1}/timesheet/entry/${id}/request`,
    APPROVE_EDIT:    (id: string | number) => `${v1}/timesheet/edit-request/${id}/approve`,
    REJECT_EDIT:     (id: string | number) => `${v1}/timesheet/edit-request/${id}/reject`,
    APPROVE_TIMEOFF: (id: string | number) => `${v1}/timesheet/time-off/${id}/approve`,
    REJECT_TIMEOFF:  (id: string | number) => `${v1}/timesheet/time-off/${id}/reject`,
  },
  SETTINGS: {
    ME:          `${v1}/settings/me`,
    PREFERENCES: `${v1}/settings/preferences`,
    PASSWORD:    `${v1}/settings/password`,
    SYSTEM:      `${v1}/settings/system`,
  },
  STARRED: {
    QUERIES:    `${v1}/starred/queries`,
    STAR_ITEM:  (item_type: string, id: string | number) => `${v1}/starred/${item_type}/${id}`,
    UNSTAR_ITEM:(item_type: string, id: string | number) => `${v1}/starred/${item_type}/${id}`,
  },
  NOTIFICATION: {
    LIST:      `${v1}/notification`,
    MARK_READ: (id: string | number) => `${v1}/notification/${id}/read`,
    READ_ALL:  `${v1}/notification/read-all`,
    DELETE:    (id: string | number) => `${v1}/notification/${id}`,
  },
  TICKET: {
    LIST:        `${v1}/ticket`,
    CREATE:      `${v1}/ticket`,
    STATS:       `${v1}/ticket/stats`,
    DETAIL:      (id: string | number) => `${v1}/ticket/${id}`,
    UPDATE:      (id: string | number) => `${v1}/ticket/${id}`,
    ATTACHMENTS: (id: string | number) => `${v1}/ticket/${id}/attachments`,
    REPLIES:     (id: string | number) => `${v1}/ticket/${id}/replies`,
  },
  MARKETING: {
    DEALS:              `${v1}/marketing/deals`,
    SALARY_BUILDER:     `${v1}/marketing/salary-builder`,
    SALARY_HISTORY:     `${v1}/marketing/salary-history`,
    PUBLISH_SALARY:     (userId: string, period: string) => `${v1}/marketing/salary-builder/${userId}/${period}/publish`,
    WON_DEALS:          `${v1}/marketing/won-deals`,
    UPWORK:             `${v1}/marketing/upwork`,
    UPWORK_ITEM:        (id: string) => `${v1}/marketing/upwork/${id}`,
    LINKEDIN:           `${v1}/marketing/linkedin`,
    LINKEDIN_ITEM:      (id: string) => `${v1}/marketing/linkedin/${id}`,
    EMAIL_LEADS:        `${v1}/marketing/email-leads`,
    EMAIL_LEADS_ITEM:   (id: string) => `${v1}/marketing/email-leads/${id}`,
    LINKEDIN_ACTIVITY:  `${v1}/marketing/linkedin-activity`,
    LEAD_ACTIVITIES:    `${v1}/marketing/lead-activities`,
    DEPOSITS:           `${v1}/marketing/deposits`,
    DEPOSIT_ITEM:       (id: string) => `${v1}/marketing/deposits/${id}`,
    DEPOSIT_TARGET:     `${v1}/marketing/deposit-target`,
    TARGETS:            `${v1}/marketing/targets`,
    MY_REPORT:          `${v1}/marketing/my-report`,
    MY_SALARIES:        `${v1}/marketing/my-salaries`,
    MEMBERS:            `${v1}/marketing/members`,
  },
  ASSET: {
    LIST:        `${v1}/asset`,
    CREATE:      `${v1}/asset`,
    CATEGORIES:  `${v1}/asset/categories`,
    LOCATIONS:   `${v1}/asset/locations`,
    VENDORS:     `${v1}/asset/vendors`,
    DETAIL:      (id: string | number) => `${v1}/asset/${id}`,
    UPDATE:      (id: string | number) => `${v1}/asset/${id}`,
    DELETE:      (id: string | number) => `${v1}/asset/${id}`,
    ASSIGN:      (id: string | number) => `${v1}/asset/${id}/assign`,
    RETURN:      (id: string | number) => `${v1}/asset/${id}/return`,
    MAINTENANCE: (id: string | number) => `${v1}/asset/${id}/maintenance`,
  },
  PERFORMANCE: {
    DAILY_REPORTS: `${v1}/performance/daily-report`,
    DAILY_REPORT:  (id: string | number) => `${v1}/performance/daily-report/${id}`,
    SCORES:        `${v1}/performance/score`,
    SCORE_BY_EMP:  (empId: string) => `${v1}/performance/score/${empId}`,
    BONUS:         `${v1}/performance/bonus`,
    CALC_BONUS:    `${v1}/performance/bonus/calculate`,
    APPROVE_BONUS: (id: string | number) => `${v1}/performance/bonus/${id}/approve`,
    PAY_BONUS:     (id: string | number) => `${v1}/performance/bonus/${id}/pay`,
  },
  // Tasks are nested under projects: /project/:projectId/tasks
  TASK: {
    LIST:   (projectId: string) => `${v1}/project/${projectId}/tasks`,
    CREATE: (projectId: string) => `${v1}/project/${projectId}/tasks`,
    DETAIL: (projectId: string, taskId: string) => `${v1}/project/${projectId}/tasks/${taskId}`,
    UPDATE: (projectId: string, taskId: string) => `${v1}/project/${projectId}/tasks/${taskId}`,
    DELETE: (projectId: string, taskId: string) => `${v1}/project/${projectId}/tasks/${taskId}`,
  },
  // Milestones are nested under projects: /project/:projectId/milestones
  MILESTONE: {
    LIST:   (projectId: string) => `${v1}/project/${projectId}/milestones`,
    CREATE: (projectId: string) => `${v1}/project/${projectId}/milestones`,
    DETAIL: (projectId: string, milestoneId: string) => `${v1}/project/${projectId}/milestones/${milestoneId}`,
    UPDATE: (projectId: string, milestoneId: string) => `${v1}/project/${projectId}/milestones/${milestoneId}`,
    DELETE: (projectId: string, milestoneId: string) => `${v1}/project/${projectId}/milestones/${milestoneId}`,
  },
  HR_PROFILE: {
    DESIGNATIONS:  `${v1}/hr-profile/designations`,
    GET:           (userId: string) => `${v1}/hr-profile/${userId}`,
    UPDATE:        (userId: string) => `${v1}/hr-profile/${userId}`,
    FULL_RECORD:   (userId: string) => `${v1}/hr-profile/${userId}/full`,
  },
  STORAGE: {
    UPLOAD: `${v1}/storage/upload`,
  },
  EMPLOYEE_DOC: {
    TYPES:   `${v1}/employee-doc/types`,
    LIST:    (userId: string) => `${v1}/employee-doc/${userId}`,
    CREATE:  (userId: string) => `${v1}/employee-doc/${userId}`,
    UPDATE:  (userId: string, docId: string) => `${v1}/employee-doc/${userId}/${docId}`,
    DELETE:  (userId: string, docId: string) => `${v1}/employee-doc/${userId}/${docId}`,
  },
  REQUISITION: {
    META:          `${v1}/requisition/meta`,
    STATS:         `${v1}/requisition/stats`,
    LIST:          `${v1}/requisition`,
    CREATE:        `${v1}/requisition`,
    DETAIL:        (id: string) => `${v1}/requisition/${id}`,
    UPDATE:        (id: string) => `${v1}/requisition/${id}`,
    SUBMIT:        (id: string) => `${v1}/requisition/${id}/submit`,
    APPROVE:       (id: string) => `${v1}/requisition/${id}/approve`,
    STATUS:        (id: string) => `${v1}/requisition/${id}/status`,
    COST:          (id: string) => `${v1}/requisition/${id}/cost`,
    CONVERT_ASSET: (id: string) => `${v1}/requisition/${id}/convert-to-asset`,
  },
  LEAVE: {
    LIST:    `${v1}/timesheet/time-off`,
    APPROVE: (id: string) => `${v1}/timesheet/time-off/${id}/approve`,
    REJECT:  (id: string) => `${v1}/timesheet/time-off/${id}/reject`,
  },
  PERMISSION: {
    MY:                 `${v1}/permission/my-permissions`,
    DEFINITIONS:        `${v1}/permission/definitions`,
    MATRIX:             `${v1}/permission`,
    ROLE:               (roleName: string) => `${v1}/permission/${roleName}`,
    USER_OVERRIDES:     (userId: string) => `${v1}/permission/users/${userId}`,
    SET_USER_OVERRIDE:  (userId: string) => `${v1}/permission/users/${userId}`,
    DEL_USER_OVERRIDE:  (userId: string, permission: string) => `${v1}/permission/users/${userId}/${encodeURIComponent(permission)}`,
    DEL_ALL_OVERRIDES:  (userId: string) => `${v1}/permission/users/${userId}`,
  },
  CRM_WORKSPACE: {
    DASHBOARD:  `${v1}/crm/dashboard`,
    HIERARCHY:  `${v1}/crm/hierarchy`,
    SUPERVISOR: (userId: string) => `${v1}/crm/users/${userId}/supervisor`,
  },
  EMPLOYEE: {
    LIST:       `${v1}/employee`,
    STATS:      `${v1}/employee/stats`,
    DETAIL:     (id: string) => `${v1}/employee/${id}`,
  },
  EDUCATION: {
    LIST:   (userId: string) => `${v1}/education-record/${userId}`,
    CREATE: (userId: string) => `${v1}/education-record/${userId}`,
    UPDATE: (userId: string, id: string) => `${v1}/education-record/${userId}/${id}`,
    DELETE: (userId: string, id: string) => `${v1}/education-record/${userId}/${id}`,
  },
  EMPLOYMENT_HISTORY: {
    LIST:   (userId: string) => `${v1}/employment-history/${userId}`,
    CREATE: (userId: string) => `${v1}/employment-history/${userId}`,
    UPDATE: (userId: string, id: string) => `${v1}/employment-history/${userId}/${id}`,
    DELETE: (userId: string, id: string) => `${v1}/employment-history/${userId}/${id}`,
  },
  INCREMENT: {
    LIST:      `${v1}/increment`,
    CALCULATE: (userId: string) => `${v1}/increment/calculate/${userId}`,
    HISTORY:   (userId: string) => `${v1}/increment/${userId}/history`,
    CREATE:    (userId: string) => `${v1}/increment/${userId}`,
    UPDATE:    (userId: string, id: string) => `${v1}/increment/${userId}/${id}`,
    DELETE:    (userId: string, id: string) => `${v1}/increment/${userId}/${id}`,
  },
  OVERTIME: {
    LIST:    `${v1}/overtime`,
    STATS:   `${v1}/overtime/stats`,
    PAYROLL: `${v1}/overtime/payroll`,
    SUBMIT:  `${v1}/overtime`,
    DETAIL:  (id: string) => `${v1}/overtime/${id}`,
    APPROVE: (id: string) => `${v1}/overtime/${id}/approve`,
    REJECT:  (id: string) => `${v1}/overtime/${id}/reject`,
    CANCEL:  (id: string) => `${v1}/overtime/${id}/cancel`,
  },
  EXPENSES: {
    SUMMARY:      `${v1}/expenses/summary`,
    ACCOUNTS:     `${v1}/expenses/accounts`,
    ACCOUNT:      (userId: string) => `${v1}/expenses/accounts/${userId}`,
    TRANSACTIONS: (userId: string) => `${v1}/expenses/accounts/${userId}/transactions`,
    TRANSACTION:  (id: string)     => `${v1}/expenses/transactions/${id}`,
    CATEGORIES:   `${v1}/expenses/categories`,
  },
  HR_REPORT: {
    ANNUAL:    (userId: string) => `${v1}/hr-report/employee/${userId}/annual`,
    MONTHLY:   (userId: string) => `${v1}/hr-report/employee/${userId}/monthly`,
    AGGREGATE: `${v1}/hr-report/aggregate`,
  },
  REPORTING: {
    PARSE:         `${v1}/reporting/parse`,
    INTERNAL_DATA: `${v1}/reporting/internal-data`,
    REPORTS:       `${v1}/reporting`,
    REPORT:        (id: string) => `${v1}/reporting/${id}`,
  },
  CHAT: {
    USERS:       `${v1}/chat/users`,
    CHANNELS:    `${v1}/chat/channels`,
    CHANNEL:     (id: string) => `${v1}/chat/channels/${id}`,
    DM:          `${v1}/chat/channels/dm`,
    GROUP:       `${v1}/chat/channels/group`,
    PRIVATE:     `${v1}/chat/channels/private`,
    JOIN:        (id: string) => `${v1}/chat/channels/${id}/join`,
    ARCHIVE:     (id: string) => `${v1}/chat/channels/${id}/archive`,
    MEMBERS:     (id: string) => `${v1}/chat/channels/${id}/members`,
    MEMBER:      (id: string, uid: string) => `${v1}/chat/channels/${id}/members/${uid}`,
    MEMBER_ROLE: (id: string, uid: string) => `${v1}/chat/channels/${id}/members/${uid}/role`,
    MESSAGES:    (id: string) => `${v1}/chat/channels/${id}/messages`,
    MESSAGE:     (id: string, msgId: string) => `${v1}/chat/channels/${id}/messages/${msgId}`,
    THREAD:      (id: string, msgId: string) => `${v1}/chat/channels/${id}/messages/${msgId}/thread`,
    REACTION:    (id: string, msgId: string) => `${v1}/chat/channels/${id}/messages/${msgId}/reactions`,
  },
} as const;

// Legacy alias — kept for any future imports, content mirrors API_ENDPOINTS
export const NEW_ENDPOINTS = API_ENDPOINTS;

export const DOWNLOADS_ENDPOINTS = {
  LATEST: `/${v1}/downloads/latest`,
  TRACK:  `/${v1}/downloads/track`,
  STATS:  `/${v1}/downloads/stats`,
} as const;
