import React, { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import Card from '@/components/ui/Card';
import Table, { Column } from '@/components/ui/Table';
import Button, { pageActionButtonClass } from '@/components/ui/Button';
import Badge from '@/components/ui/Badge';
import { useToastContext } from '@/components/toast/ToastProvider';
import { apiRequest } from '@/lib/queryClient';
import { API_ENDPOINTS } from '@/services/api/endpoints';
import { DollarSign, Users, TrendingDown, Plus, X, ChevronLeft, Printer } from 'lucide-react';
import { cn } from '@/utils/cn';

// ─── Types ────────────────────────────────────────────────────────────────────
type RunStatus = 'DRAFT' | 'PROCESSING' | 'COMPLETED' | 'PAID';

interface PayrollRun {
  id: string;
  period_month: number;
  period_year: number;
  status: RunStatus;
  total_gross: number;
  total_net: number;
  total_deductions: number;
  employee_count: number;
  created_at: string;
}

interface PayrollEntry {
  id: string;
  user_id: string;
  base_salary: number;
  present_days: number;
  working_days: number;
  paid_leave_days: number;
  unpaid_leave_days: number;
  absent_days: number;
  late_violation_count: number;
  late_deduction: number;
  absence_penalty: number;
  overtime_amount: number;
  bonus_amount: number;
  gross_amount: number;
  tax_amount: number;
  deductions: number;
  net_amount: number;
  calculated_net_amount: number;
  validation_status: 'PASSED' | 'FAILED';
  validation_reason: string | null;
  status: string;
  user?: { id: string; first_name: string; last_name: string; email: string };
  run?: { period_month: number; period_year: number };
}

// ─── Helpers ──────────────────────────────────────────────────────────────────
const STATUS_COLORS: Record<RunStatus, string> = {
  DRAFT:      'bg-gray-100 text-gray-600',
  PROCESSING: 'bg-amber-100 text-amber-700',
  COMPLETED:  'bg-green-100 text-green-700',
  PAID:       'bg-blue-100 text-blue-700',
};

const fmt = (n: number) => `PKR ${n.toLocaleString()}`;

function printPayslip(entry: PayrollEntry) {
  const html = `
    <html><head><title>Payslip</title><style>
      body{font-family:sans-serif;padding:40px;max-width:600px;margin:0 auto}
      h1{color:#005CDA}table{width:100%;border-collapse:collapse;margin:16px 0}
      td,th{padding:8px 12px;border:1px solid #e5e7eb;text-align:left}
      th{background:#f9fafb;font-weight:600}.total{font-weight:700;background:#eff6ff}
      .validation-warning{background:#fef2f2;border:1px solid #fecaca;color:#b91c1c;padding:12px 16px;border-radius:8px;font-size:13px;margin:16px 0}
    </style></head><body>
      <h1>TekXAI</h1>
      <h2>Pay Slip — ${entry.run?.period_month}/${entry.run?.period_year}</h2>
      <p><strong>Employee:</strong> ${entry.user?.first_name} ${entry.user?.last_name}</p>
      <p><strong>Email:</strong> ${entry.user?.email}</p>
      ${entry.validation_status === 'FAILED' ? `<div class="validation-warning"><strong>Validation Failed:</strong> ${entry.validation_reason || 'Negative net pay.'}</div>` : ''}
      <table>
        <tr><th>Component</th><th>Amount (PKR)</th></tr>
        <tr><td>Base Salary</td><td>${entry.base_salary.toLocaleString()}</td></tr>
        <tr><td>Present Days</td><td>${entry.present_days} / ${entry.working_days}</td></tr>
        <tr><td>Paid Leave Days</td><td>${entry.paid_leave_days ?? 0}</td></tr>
        <tr><td>Unpaid Leave Days</td><td>${entry.unpaid_leave_days ?? 0}</td></tr>
        <tr><td>Absent Days</td><td>${entry.absent_days ?? 0}</td></tr>
        <tr><td>Overtime</td><td>${entry.overtime_amount.toLocaleString()}</td></tr>
        <tr><td>Bonus</td><td>${entry.bonus_amount.toLocaleString()}</td></tr>
        <tr><td>Gross Earnings</td><td>${entry.gross_amount.toLocaleString()}</td></tr>
        <tr><td>Tax Deduction</td><td>(${entry.tax_amount.toLocaleString()})</td></tr>
        <tr><td>Late Deduction${entry.late_violation_count ? ` (${entry.late_violation_count} occurrence${entry.late_violation_count === 1 ? '' : 's'})` : ''}</td><td>(${(entry.late_deduction ?? 0).toLocaleString()})</td></tr>
        <tr><td>Absence Penalty</td><td>(${(entry.absence_penalty ?? 0).toLocaleString()})</td></tr>
        <tr><td>Total Deductions</td><td>(${entry.deductions.toLocaleString()})</td></tr>
        <tr class="total"><td>Net Pay</td><td>${entry.net_amount.toLocaleString()}</td></tr>
      </table>
      <p style="margin-top:40px;color:#6b7280;font-size:12px">Generated by TekXAI ERP</p>
    </body></html>`;
  const w = window.open('', '_blank');
  w?.document.write(html);
  w?.document.close();
  w?.print();
}

// ─── Summary Card ─────────────────────────────────────────────────────────────
const SummaryCard: React.FC<{ icon: React.ReactNode; label: string; value: string; color: string }> = ({ icon, label, value, color }) => (
  <Card className="border-none shadow-sm p-5 flex items-center gap-4">
    <div className={cn('w-11 h-11 rounded-xl flex items-center justify-center shrink-0', color)}>
      {icon}
    </div>
    <div>
      <p className="text-[11px] font-black uppercase tracking-widest text-gray-400">{label}</p>
      <p className="text-xl font-black text-gray-900 mt-0.5">{value}</p>
    </div>
  </Card>
);

// ─── New Run Modal ─────────────────────────────────────────────────────────────
const NewRunModal: React.FC<{ open: boolean; onClose: () => void; onCreate: (m: number, y: number) => void; loading: boolean }> = ({ open, onClose, onCreate, loading }) => {
  const now = new Date();
  const [month, setMonth] = useState(now.getMonth() + 1);
  const [year, setYear]   = useState(now.getFullYear());

  if (!open) return null;
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      <div className="absolute inset-0 bg-black/30 backdrop-blur-sm" onClick={onClose} />
      <div className="relative bg-white rounded-2xl shadow-2xl p-8 w-full max-w-sm z-10 flex flex-col gap-5">
        <div className="flex items-center justify-between">
          <h3 className="text-lg font-black text-gray-900">New Payroll Run</h3>
          <button onClick={onClose} className="p-1.5 rounded-lg hover:bg-gray-100 text-gray-400"><X size={18} /></button>
        </div>
        <div className="flex gap-3">
          <div className="flex flex-col gap-1 flex-1">
            <label className="text-[10px] font-black uppercase tracking-widest text-gray-400">Month</label>
            <select value={month} onChange={(e) => setMonth(Number(e.target.value))}
              className="h-10 px-3 rounded-xl border border-gray-200 text-sm font-bold outline-none focus:ring-2 focus:ring-primary-100">
              {Array.from({ length: 12 }, (_, i) => (
                <option key={i + 1} value={i + 1}>{new Date(2000, i).toLocaleString('default', { month: 'long' })}</option>
              ))}
            </select>
          </div>
          <div className="flex flex-col gap-1 flex-1">
            <label className="text-[10px] font-black uppercase tracking-widest text-gray-400">Year</label>
            <input type="number" value={year} onChange={(e) => setYear(Number(e.target.value))} min={2020} max={2030}
              className="h-10 px-3 rounded-xl border border-gray-200 text-sm font-bold outline-none focus:ring-2 focus:ring-primary-100" />
          </div>
        </div>
        <Button variant="primary" fullWidth className="h-11 rounded-xl font-black" onClick={() => onCreate(month, year)} disabled={loading}>
          {loading ? 'Creating...' : 'Create Run'}
        </Button>
      </div>
    </div>
  );
};

// ─── Main Component ────────────────────────────────────────────────────────────
const PayrollPage: React.FC = () => {
  const toast = useToastContext();
  const qc    = useQueryClient();
  const [selectedRunId, setSelectedRunId] = useState<string | null>(null);
  const [showNewModal, setShowNewModal]  = useState(false);

  // Fetch payroll runs
  const { data: runsData, isLoading: runsLoading } = useQuery({
    queryKey: ['payroll-runs'],
    queryFn: () => apiRequest<any>(API_ENDPOINTS.PAYROLL.LIST).then((r) => r?.payload || []),
  });
  const runs: PayrollRun[] = Array.isArray(runsData) ? runsData : (runsData?.records || []);
  // Derived from the live runs query (not a locally-captured snapshot) so
  // the Run Detail header always reflects the current status — invalidating
  // ['payroll-runs'] after Calculate now refreshes this too, not just the table.
  const selectedRun: PayrollRun | null = selectedRunId ? runs.find((r) => r.id === selectedRunId) || null : null;

  // Fetch run entries when a run is selected
  const { data: entriesData, isLoading: entriesLoading } = useQuery({
    queryKey: ['payroll-entries', selectedRun?.id],
    queryFn: () => apiRequest<any>(API_ENDPOINTS.PAYROLL.GET(selectedRun!.id)).then((r) => r?.payload?.entries || []),
    enabled: !!selectedRun,
  });
  const entries: PayrollEntry[] = Array.isArray(entriesData) ? entriesData : [];

  // Create run mutation
  const createRun = useMutation({
    mutationFn: (body: { period_month: number; period_year: number }) =>
      apiRequest(API_ENDPOINTS.PAYROLL.CREATE, { method: 'POST', body: JSON.stringify(body) }),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['payroll-runs'] });
      setShowNewModal(false);
      toast.success('Payroll run created');
    },
    onError: (e: any) => toast.error(e?.message || 'Failed to create run'),
  });

  // Calculate run mutation
  const calculateRun = useMutation({
    mutationFn: (id: string) =>
      apiRequest(API_ENDPOINTS.PAYROLL.CALCULATE(id), { method: 'POST', body: '{}' }),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['payroll-runs'] });
      qc.invalidateQueries({ queryKey: ['payroll-entries', selectedRun?.id] });
      toast.success('Calculation started');
    },
    onError: (e: any) => toast.error(e?.message || 'Failed to calculate'),
  });

  // Summary
  const latest = runs[0];
  const totalGross = runs.reduce((s, r) => s + (r.total_gross || 0), 0);
  const totalDeductions = runs.reduce((s, r) => s + (r.total_deductions || 0), 0);
  const totalEmployees = latest?.employee_count || 0;

  const runCols: Column<PayrollRun>[] = [
    {
      header: 'Period', key: 'period_month',
      render: (r) => <span className="font-black text-gray-900">{new Date(r.period_year, r.period_month - 1).toLocaleString('default', { month: 'long', year: 'numeric' })}</span>,
    },
    {
      header: 'Status', key: 'status',
      render: (r) => <span className={cn('px-2.5 py-1 rounded-lg text-xs font-black uppercase', STATUS_COLORS[r.status])}>{r.status}</span>,
    },
    {
      header: 'Total Gross', key: 'total_gross',
      render: (r) => <span className="font-bold text-gray-700">{fmt(r.total_gross || 0)}</span>,
    },
    {
      header: 'Total Net', key: 'total_net',
      render: (r) => <span className="font-bold text-green-600">{fmt(r.total_net || 0)}</span>,
    },
    {
      header: 'Employees', key: 'employee_count',
      render: (r) => <span className="font-bold">{r.employee_count || 0}</span>,
    },
    {
      header: 'Actions', key: 'id', align: 'right',
      render: (r) => (
        <div className="flex items-center justify-end gap-2">
          <button onClick={() => setSelectedRunId(r.id)}
            className="px-3 py-1.5 text-xs font-black rounded-lg bg-primary-50 text-primary-600 hover:bg-primary-100 transition-colors">
            View
          </button>
          {(r.status === 'DRAFT' || r.status === 'PROCESSING') && (
            <button onClick={() => calculateRun.mutate(r.id)}
              disabled={calculateRun.isPending}
              className="px-3 py-1.5 text-xs font-black rounded-lg bg-amber-50 text-amber-700 hover:bg-amber-100 transition-colors disabled:opacity-50">
              Calculate
            </button>
          )}
        </div>
      ),
    },
  ];

  const entryCols: Column<PayrollEntry>[] = [
    {
      header: 'Employee', key: 'user_id',
      render: (r) => <span className="font-black text-gray-900">{r.user ? `${r.user.first_name} ${r.user.last_name}` : r.user_id?.slice(0, 8)}</span>,
    },
    { header: 'Base Salary', key: 'base_salary', render: (r) => fmt(r.base_salary) },
    {
      header: 'Attendance', key: 'present_days',
      render: (r) => <span className="font-bold">{r.present_days} / {r.working_days}</span>,
    },
    {
      header: 'Leave / Absent', key: 'paid_leave_days',
      render: (r) => (
        <span className="text-xs font-bold text-gray-500">
          {r.paid_leave_days || 0} paid · {r.unpaid_leave_days || 0} unpaid
          {(r.absent_days || 0) > 0 && <span className="text-red-500"> · {r.absent_days} absent</span>}
        </span>
      ),
    },
    { header: 'Overtime', key: 'overtime_amount', render: (r) => fmt(r.overtime_amount) },
    { header: 'Bonus', key: 'bonus_amount', render: (r) => fmt(r.bonus_amount) },
    { header: 'Gross', key: 'gross_amount', render: (r) => <span className="font-bold">{fmt(r.gross_amount)}</span> },
    { header: 'Deductions', key: 'deductions', render: (r) => <span className="text-red-500 font-bold">({fmt(r.deductions)})</span> },
    {
      header: 'Net Pay', key: 'net_amount',
      render: (r) => (
        <div className="flex flex-col gap-0.5">
          <span className={cn('font-black', r.validation_status === 'FAILED' ? 'text-red-600' : 'text-green-600')}>
            {fmt(r.net_amount)}
          </span>
          {r.validation_status === 'FAILED' && (
            <span className="text-[10px] font-bold text-red-500 max-w-[220px]" title={r.validation_reason || ''}>
              Validation failed — calculated {fmt(r.calculated_net_amount)}
            </span>
          )}
        </div>
      ),
    },
    {
      header: 'Status', key: 'status',
      render: (r) => <span className="px-2 py-0.5 rounded-lg text-xs font-bold bg-gray-100 text-gray-600">{r.status}</span>,
    },
    {
      header: '', key: 'id', align: 'right',
      render: (r) => (
        <button
          onClick={() => printPayslip({ ...r, run: selectedRun ? { period_month: selectedRun.period_month, period_year: selectedRun.period_year } : r.run })}
          className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-black rounded-lg bg-gray-50 text-gray-600 hover:bg-gray-100 transition-colors"
        >
          <Printer size={13} /> Payslip
        </button>
      ),
    },
  ];

  return (
    <div className="flex flex-col gap-8 pb-10">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-black text-gray-900 tracking-tight">Payroll</h1>
          <p className="text-sm text-gray-500 font-medium mt-1">Manage payroll runs, review entries, and download payslips.</p>
        </div>
        {!selectedRun && (
          <Button variant="primary" leftIcon={Plus} className={pageActionButtonClass} onClick={() => setShowNewModal(true)}>
            New Run
          </Button>
        )}
      </div>

      {!selectedRun ? (
        <>
          {/* Summary Cards */}
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
            <SummaryCard icon={<DollarSign size={20} className="text-primary-600" />} label="Total Payroll" value={fmt(totalGross)} color="bg-primary-50" />
            <SummaryCard icon={<Users size={20} className="text-purple-600" />} label="Employees" value={String(totalEmployees)} color="bg-purple-50" />
            <SummaryCard icon={<TrendingDown size={20} className="text-red-500" />} label="Deductions" value={fmt(totalDeductions)} color="bg-red-50" />
            <SummaryCard
              icon={<span className="text-xs font-black">{latest?.status || 'N/A'}</span>}
              label="Current Status"
              value={latest ? new Date(latest.period_year, latest.period_month - 1).toLocaleString('default', { month: 'short', year: 'numeric' }) : '—'}
              color={latest ? STATUS_COLORS[latest.status].split(' ')[0] : 'bg-gray-50'}
            />
          </div>

          {/* Runs Table */}
          <Card className="border-none shadow-sm">
            <Table columns={runCols} data={runs} isLoading={runsLoading} emptyMessage="No payroll runs yet. Create the first run." />
          </Card>
        </>
      ) : (
        <>
          {/* Run Detail */}
          <div className="flex items-center gap-3">
            <button onClick={() => setSelectedRunId(null)} className="flex items-center gap-1.5 text-sm font-bold text-gray-500 hover:text-gray-800 transition-colors">
              <ChevronLeft size={16} /> Back to runs
            </button>
            <div className="h-4 w-px bg-gray-200" />
            <h2 className="text-lg font-black text-gray-900">
              {new Date(selectedRun.period_year, selectedRun.period_month - 1).toLocaleString('default', { month: 'long', year: 'numeric' })}
            </h2>
            <span className={cn('px-2.5 py-1 rounded-lg text-xs font-black uppercase', STATUS_COLORS[selectedRun.status])}>{selectedRun.status}</span>
          </div>
          <Card className="border-none shadow-sm">
            <Table columns={entryCols} data={entries} isLoading={entriesLoading} emptyMessage="No entries for this run. Run Calculate to generate them." />
          </Card>
        </>
      )}

      <NewRunModal
        open={showNewModal}
        onClose={() => setShowNewModal(false)}
        onCreate={(m, y) => createRun.mutate({ period_month: m, period_year: y })}
        loading={createRun.isPending}
      />
    </div>
  );
};

export default PayrollPage;
